### ISSUE TITLE
Container-sync uncaught exception, wrong path?

### ISSUE THREAD

**Issue by HadesArchitect** [ccollicutt/docker-swift-onlyone#4]
> container-sync: UNCAUGHT EXCEPTION#012Traceback (most recent call last):#012  File "/usr/bin/swift-container-sync", line 23, in <module>#012    run_daemon(ContainerSync, conf_file, **options)#012  File "/usr/lib/python2.7/dist-packages/swift/common/daemon.py", line 110, in run_daemon#012    klass(conf).run(once=once, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/common/daemon.py", line 57, in run#012    self.run_forever(**kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/container/sync.py", line 173, in run_forever#012    for path, device, partition in all_locs:#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 1721, in audit_location_generator#012    partitions = listdir(datadir_path)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2160, in listdir#012    return os.listdir(path)#012OSError: [Errno 20] **Not a directory: '/srv/container.ring.gz/containers'**

**/srv/container.ring.gz** is an archive, perhaps the correct path is a **/srv/sdb1/containers**? I could make a PR but I don't know where to fix the path.

**Comment by ccollicutt** [comment]
I think it's because I have /srv as the path in container-server.conf. I should probably change this, as usually it's something like /srv/node so the dev path becomes /srv/node/somedev. Then I have the ring files on /srv too so the process I guess scans that dir and finds the ring file.

So yeah, if you wanted to look at the config files and work on changing the path to be /srv/node that'd be great. :) That would affect a lot of things though, so there would be a few changes to make.

**Comment by ccollicutt** [comment]
I know this was a billion years ago, but I just moved the devices into /srv/node so I can close this now.
